name: Medical_Expenses

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read
0
jobs: 
  build:
    run-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set Up Python 3.11
        uses: actions/checkout@v3
        with: 
          Python-version: 3.11